### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NicoGonzalez94** [Tomas-Leon/13-trabajoFinal#29]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar el logo junto con el nombre de la pagina.

## Resultado actual

• No se encuentra el logo. (En ninguna sección de la pagina)

## Captura

![image](https://github.com/user-attachments/assets/0e710e87-cc16-4258-81bc-56930471cf0d)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Santi-Olivera** [comment]
Ya se encuentra realizado para su chequeo
