### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by NicoGonzalez94** [Tomas-Leon/13-trabajoFinal#30]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que al hacer click en el logo ubicado en el footer me redirija a la pagina principal (inicio).
• Que al hacer click en las redes sociales estos redirijan a dicho sitio o una page 404.
• Encontrar algún tipo de información sobre contacto (Agregar numero de tel, una dirección y mail).

## Resultado actual

• Al hacer click en el logo ubicado en el footer no cumple ninguna acción.
• Los botones de redes sociales no sirven.
• No se encuentra ninguna información sobre contacto.

## Captura

![image](https://github.com/user-attachments/assets/bad899e3-cf28-4827-8759-ed6da7a268ec)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Santi-Olivera** [comment]
Ya se encuentra realizado para su chequeo
