### ISSUE TITLE
Boton sin accion

### ISSUE THREAD

**Issue by NicoGonzalez94** [Tomas-Leon/13-trabajoFinal#31]
## Proceso

1. Ingrese a la pagina.
2. Quise usar el buscador.

## Resultado esperado

• Que el botón cumpla dicha acción o redirija a una page 404.

## Resultado actual

• El buscador no cumple ninguna funcion.

## Captura

![image](https://github.com/user-attachments/assets/6ec99fd6-ea3a-463d-8131-7505f9214c35)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Santi-Olivera** [comment]
Ya se encuentra realizado para su chequeo
